name: Terraform Azure Deployment

on:
  push:
    branches:
      - master ## Change to your branch name ##

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code ## To checkout the source code ##
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.14 ## Set preferred Terraform version ##

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      run: terraform apply -auto-approve

    - name: Terraform Destroy
      run: terraform destroy -auto-approve
